### PR TITLE
Require authentication before process to send mail steps

### PR DESCRIPTION
**Pull request by tdtgit**
Even we bind them to a "private worker", an addition steps is recommended: https://developers.cloudflare.com/workers/configuration/bindings/about-service-bindings/#gateway-worker-and-service-bindings-usage

### CODE REVIEW

**Comment by winstxnhdw** [comment]
I don't think this would work? You've not populated the `Config` file.

**Comment by tdtgit** [comment]
Added the config. Do you think it is required or can be optional?

**Comment by winstxnhdw** [comment]
I think it should be optional.

**Review by winstxnhdw — CHANGES_REQUESTED** [review]
nit. Just style change. The codebase uses snake_case.

**Comment by winstxnhdw** [comment]
LGTM. Thanks!

**Pull request merged**
